name: 'sample_project'
version: '1.0.0'
config-version: 2
profile: 'sample_project'

model-paths: ["models"]
target-path: "target"

models:
  sample_project:
    staging:
      +materialized: view
    marts:
      +materialized: table
